Use vite-plugin-dts to gen and export index.d.ts
With Typescript types properted now we can remove most of the duplicates
in packages/app - all except SchemaCategory. Also export allIngredients
so that all the .json files in data/ingredients only have to be accessed
in one place - eventually they should be moved under sci-cream crate.

Note that importing @workspace/sci-cream in seed.ts would previously
cause an error (below) when seeding, the same one in schema.ts that
necessitated the implementation of SchemaCategory. This issue is
addressed by setting "type": "module" in packages/app/package.json.

  ERROR: Top-level await is currently not supported with the "cjs