Fix ts/prop_key.ts missing from code coverage
In prop_key.test.ts, if we import, say `prop_key_as_med_str_js`, from
"../../dist/index" instead of "./prop_key", then 'prop_key.ts' won't
show up in code coverage reports. However, doing that causes an error:
  Error: "ESM integration proposal for Wasm" is not supported currently.

Fix the above error by using plugins "vite-plugin-wasm" and
"vite-plugin-top-level-await" in vitest.config.mjs.